server:
  port: 10000
spring:
  data:
    mongodb:
      uri: mongodb://192.168.1.13:27017/reactive
      username: admin
      password: doporro@1234
  r2dbc:
    url: r2dbc:postgresql://192.168.1.13:5432/reactive?serverZoneId=GMT%2B8
    username: postgres
    password: doporro@1234
    pool:
      initialSize: 100
      maxSize: 200
      maxCreateConnectionTime: 30s

  main:
    web-application-type: reactive
